#!/bin/sh

# Since the wattsup is a bit... crashy... this script restarts the app so long
# as it exits poorly.

# Based on http://superuser.com/a/223454

# Ensure we shut down the wattsup on a termination signal.
_term() {
   kill -TERM "$PID"
   exit
}

trap _term HUP INT TERM

RC=1
while [ $RC -ne 0 ]; do
   ./wattsup "$@" &
   PID=$!
   wait $PID
   RC=$?
done

# Reset the terminal handler.
trap - TERM HUP INT
